# QT
set(QT_REQUIRED_VERSION "5.10.1")
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

if(CMAKE_VERSION VERSION_LESS "3.7.0")
    set(CMAKE_INCLUDE_CURRENT_DIR ON)
endif()

set(QT_PREFIX ${CMAKE_SOURCE_DIR}/Externals/Qt5/msvc2017_64/)
list(APPEND CMAKE_PREFIX_PATH ${QT_PREFIX})

find_package(Qt5 ${QT_REQUIRED_VERSION} REQUIRED COMPONENTS Core Gui Widgets)
include(QtPropertyBrowser)
#add_subdirectory(${CMAKE_SOURCE_DIR}/Externals/Qt5/QtPropertyBrowser ${CMAKE_BINARY_DIR}/test)
